# Generated by Django 4.1.7 on 2023-03-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
